### ISSUE TITLE
Implementation of measurements of harmonics 

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [voicesauce/opensauce-python#40]
It seems that opensauce-python only implements various methods to extract f0 and formants, which voicesauce had more measures implemented, right? 

Opensauce is stated to not be updated anymore, so I guess harmonic amplitudes and cpp will be implemented here? Or is VoiceSauce actually the most updated version still? Perhaps the state of packages needs to be clarified so the user may know which one to use.

 It seems now that the praatsauce port may be the most up-to-date right now?
https://github.com/kirbyj/praatsauce

**Comment by krismyu** [comment]
Hi Frederik, thank you for your note! We had been working on implementing the harmonic amplitudes and CPP, but it turned out unfortunately that porting from Matlab to Python ended up being surprisingly trickier than anticipated and the personnel working on this left the project.  I am hoping to resume work on this soon, but in the meantime, I would recommend using VoiceSauce, the Matlab version, if you have access to Matlab (or can use the standalone version, if you have a PC), and if you want the most updated version.

PraatSauce is also not a complete port, most importantly because it does not have the F0 implemented with the straight algorithm, which affects computations downstream, but it is much more complete than the python port in progress here and is useable in its current state for voice measures, unlike the software here. So it's a good alternative if you can't use VoiceSauce (the Matlab version).

**Comment by FredrikKarlssonSpeech** [comment]
Thank you for the reply. I see the problem. However, I feel that I need to report here then, as I cant find a github page or similar where I can post voicesauce issues, that I am having huge problems running the analysis on in OSX. The issue seems to be that the snack library is considered not verified by the OS. I disable all snack analyses, but somewhere VoiceSauce still uses snack to do parts of the analysis, so I get no measurements out of it.
